name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: read

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
            go-version-file: go.mod
            cache-key-suffix: task-backend
      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: |
            go install github.com/jstemmer/go-junit-report@latest
            go test -v ./... | go-junit-report > report.xml
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always() # Show even on failure
        with:
          name: TaskPilot Backend Unit Tests
          path: report.xml
          reporter: java-junit

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ vars.DOCKER_IMAGE_NAME}}:${{ github.sha }}
